name: orderit
description: "AmPower OrderIT - the B2B Catalogue and Order Booking system built on top of ERPNext"

publish_to: "none"

version: 2.0.1+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  connectivity_plus: ^5.0.2
  crypto: ^3.0.2
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  file_picker: ^8.0.3
  flutter_form_builder: ^7.8.0
  flutter_html: ^3.0.0-alpha.6
  flutter_typeahead: ^5.2.0
  flutter_widget_from_html_core: ^0.16.0
  fluttertoast: ^8.2.12
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  injectable: null
  intl: ^0.17.0
  json_table: ^2.0.1
  logger: ^2.0.2+1
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^11.0.0
  provider: ^6.0.5
  rflutter_alert: ^2.0.7
  rive: ^0.12.4
  shared_preferences: ^2.1.0
  timeago: ^3.3.0
  url_launcher: ^6.3.1
  uuid:
  form_builder_validators: ^9.1.0
  share_plus: ^10.1.2
  image_picker: ^1.0.1
  camera: ^0.10.5+2
  flutter_layout_grid: ^2.0.5
  flutter_styled_toast: ^2.2.1
  html: ^0.15.4
  package_info_plus: ^4.2.0
  data_table_2: ^2.5.12
  flutter_native_splash: ^2.4.1
  cookie_jar: any
  url_launcher_ios: ^6.3.1
  open_filex: ^4.7.0
  flutter_upgrade_version: ^1.1.7
  photo_view: ^0.15.0
  skeletonizer: ^1.4.3

dev_dependencies:
  build_runner:
  build_web_compilers:
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: null
  flutter_lints: ^4.0.0
  archive: ^3.6.1

dependency_overrides:
  intl: ^0.18.0
  http: ^1.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ampower_orderit_logo_with_bg.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/ampower_orderit_logo_with_bg.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/ampower_orderit_logo_with_bg.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/ampower_orderit_logo_with_bg.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/gif/
    - assets/illustrations/
    - assets/rive_assets/
    - fonts/

flutter_native_splash:
  android_12:
  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  android: false
  ios: false
